author: 'Ricardo SIGNES <rjbs@cpan.org>'
distribution_type: module
generated_by: Module::Install version 0.62
license: perl
name: Rubric-Entry-Formatter-KwikiFormatish
no_index:
  directory:
    - inc
    - t
requires:
  Rubric: 0.1302
  Text::KwikiFormatish: 1.10
version: 0.551
